---
- include_tasks: check.yaml

- block:
  - include_tasks: common/get_xdr_agent_download_url.yaml
  - name: create temp install directory
    win_file:
      path: "{{ xdr_windows_temp_path }}"
      state: directory
  - ansible.builtin.set_fact:
      xdr_msi_location: "{{ xdr_windows_temp_path }}\\{{ xdr_agent_filename }}"
  - name: download installer
    win_get_url:
      url: "{{ xdr_agent_download_url }}"
      dest: "{{ xdr_msi_location }}"
      headers: "{{ xdr_auth_headers }}"
  - name: install XDR msi
    win_package:
      path: "{{ xdr_msi_location }}"
      product_id: "{{ xdr_msi_product_id }}"
      arguments: "/l*v {{ xdr_windows_temp_path }}\\agentinstall.log /qn {{ xdr_install_type }}"
  when: >
    not xdr_installed|bool or
    xdr_installed_version|default(0,true) is version(xdr_version_windows, operator='<') or
    xdr_force|bool
