- name: set request body
  set_fact:
    xdr_get_dist_url_request_data:
      request_data:
        distribution_id: "{{ xdr_agent_distribution_id }}"
        package_type: "{{ xdr_package_type }}"
- name: get XDR agent download uri
  delegate_to: localhost
  become: no
  uri:
    url: "{{ xdr_base_uri }}/public_api/v1/distributions/get_dist_url/"
    method: POST
    return_content: yes
    headers: "{{ xdr_auth_headers }}"
    body_format: json
    body: "{{ xdr_get_dist_url_request_data | to_json }}"
  register: package_data
  ignore_errors: yes
- name: register download URL Fact
  set_fact:
    xdr_agent_download_url: "{{ package_data.json.reply.distribution_url }}"
  when: package_data.json.reply.distribution_url is defined
- name: report errors
  fail:
    msg: "Error - {{ package_data.json.reply.err_extra | default('unknown error getting package URL') }} Request: {{ xdr_get_dist_url_request_data | to_json }}"
  when: package_data.status != 200